ignitho.api:
    type: rest
    name_prefix: api_1_
    prefix: /v1
    resource: 'Ignitho\ApiBundle\Controller\ApiController'

post_page:
    type: rest
    prefix: /v1
#    parent: ignitho.api
    resource: 'Ignitho\ApiBundle\Controller\PageApiController'
