parameters:
    ignitho.api.handler.class: Ignitho\ApiBundle\Handler\ApiHandler
    ignitho.admin.entity.page.class: Ignitho\AdminBundle\Entity\Page
    ignitho.admin.form.page.class: Ignitho\AdminBundle\Form\PageType

services:
    ignitho.api.page.handler:
        class: '%ignitho.api.handler.class%'
        arguments: ['@doctrine.orm.entity_manager', '%ignitho.admin.entity.page.class%', '%ignitho.admin.form.page.class%', '@form.factory', '@service_container']
