ignitho.admin.login:
    path: /login
    defaults: { _controller: IgnithoAdminBundle:Security:login }

ignitho.admin.register:
    path:     /register
    defaults: { _controller: IgnithoAdminBundle:Registration:register }
    prefix: /

ignitho.admin.front_page:
    path:     /
    defaults: { _controller: IgnithoAdminBundle:Welcome:frontPage }
    prefix: /
