ignitho.admin.login:
    path: /login
    defaults: { _controller: IgnithoAdminBundle:Security:login }

ignitho.admin.home:
    path: /home
    defaults: { _controller: IgnithoAdminBundle:Admin:home }
    prefix: /admin

ignitho.admin.welcome:
    path:     /
    defaults: { _controller: IgnithoAdminBundle:Page:welcome }

ignitho.admin.register:
    path:     /register
    defaults: { _controller: IgnithoAdminBundle:Registration:register }
