ignitho.admin.admin_page:
    resource: "@IgnithoAdminBundle/Resources/config/routing/page.yml"
    prefix:   /admin/page

ignitho.admin.login:
    path: /login
    defaults: { _controller: IgnithoAdminBundle:Security:login }

ignitho.admin.home:
    path: /home
    defaults: { _controller: IgnithoAdminBundle:Admin:home }
    prefix: /admin

ignitho.admin.register:
    path:     /register
    defaults: { _controller: IgnithoAdminBundle:Registration:register }

ignitho.admin.front_page:
    path:     /
    defaults: { _controller: IgnithoAdminBundle:Welcome:frontPage }
