services:
    ignitho.admin.service.page_controller:
        class: Ignitho\AdminBundle\Controller\PageController
        arguments: ['@doctrine.orm.entity_manager', '@ignitho.admin.service.request']

    ignitho.admin.service.request:
        class: Symfony\Component\HttpFoundation\Request

    Symfony\Component\HttpFoundation\Request: '@ignitho.admin.service.request'
